---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: db-secret
  namespace: default
spec:
  encryptedData:
    DATABASE_URL: AgCLylNgIxWuEP3EfLNOOFefeOuylNI3/+7S3xvktyJKQXdMQI4/ECCjBjZl9ECu87kktZxaiOqYq/pWtGdbWwHYOy9Y2LxC9GkofMfcDFyszlsdZ96uA4PySxDS33jW+387o2fC4k4fOKa8Oo70tXhqzziL94KmBmmWvuYzFMGBRWoDdU+S3gj+5gZCYIgnnlzkKO6fUEdF+fOgy4/qCrP50ovErvEcESMN6/C9Esp8741VOJHSqekuaygMoacZLQtVDnTbObzMwpIhguBOV853QdWlnOzR6sX9wykyNJQ3NwGnNZc7XS8uYno4GlZag7CzlgfwThImN3f+wXXPMRmEXi/GCkR7fGXXaP36socf8o8rMtLhZGJysM18yK6thrMYPcXqJhhe5w8TtdEyEDqSZVTuOhWOX70V9kJqwX6INlEa4M9ijDKGKtQYisKun91ZUvxIEevQjqh8KOfTvjhw8Xttcf96edUH/JY67YtmY+JvCfBNaDBj34IfzixNpkWz1orDkrOJHTqB99fbSTkYANKI4YH9Zy0Rq3bqWB4MTDp3hQiupXTRr786w+nkvJ+JtYn5pgZtkGlcMgqirJFX8roDP8b2Zvi7euHS1sMnqwKLxn5wNtqXvo816L8NT3XEXbsYJkjvWo9qUjYWDiraWKFGN1iQ+t3iDxkbatJ7ESL9L7jqjIXph9AHKzldJ414KyRTu5K45ZX2ZYlCVhJlGlXy8PJ0hlnjUKT72J7vRfSRz01LhjpAEVvk5yxnbVJ5peExM7LGCQ==
  template:
    metadata:
      name: db-secret
      namespace: default
