---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: db-secret
  namespace: default
spec:
  encryptedData:
    DATABASE_URL: AgCfukDVh3o8YSXL1RN/WgECjbVfFrZpDFQQ87QrdSi65nkzc6BkVzcGmg1eQbVqZBoy8x2XaUs4z/79BGyDEOIGib6fspj4e7Rjdx4EXdy/Aax1Fc2QXSOB5v3tTp87SQSSnLTC1Ph94/b4yOIJNN4l4Vu2gOFoQnRiHN0FQBOB+61nqtGdw75BfUfit4NflCylL/Mv2VSkcfVWmfhiBGLBFhEFbLnO1UithsdK/arteWLN/7VvJMKulOxEmm2Q8nGVOH8YoJXyXMdfOBMRtusQY/wisOeLUBKsvKXQr7YffM/+CjLNGvc9XYL14KOtGew31vOSpbzjU4VatQZ+8gGF0+k2wcVKCbJZq0rWx0DP7CfEAbSNcTcfPiM9s4VBu2ZETKeuyE3NQkmUK5oyGvNzOe0muQoxLzzwcImdbpEJ4LwIZp4xJZsw6QSCPtCN1TAtF3COi7VHmEHKKO0GdqK7lRbDKiqJaC8jJdWdekXSfwMthbtHzFyfnEo0jPWEXFORPCgZDc8rGQjTjeY/1vVTt8guIaFSAL1i5oA//QM/4x2/1HvtsWpWzSaly7mD51+iVWda0J7utIMc3L6CFSlV2sjlSzjiic5EvKZofVdOcti7TVv+gEKV+9zdIlDQ2h/lN85soxSCZy2U/DOvGng0dn1B60GLHDjoGSquFFfy5cYzp+cemedZahXbPm8ZRu9GQTwgmAfQ/O9YoaUxWIvsHTGGpzIqydQikLNBZEnEQtOSIc6oXspMw/s01KjSfXDmCc4uslhaQw==
  template:
    metadata:
      name: db-secret
      namespace: default
